# Generated by Django 6.0.4 on 2026-04-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Заголовок")),
                (
                    "description",
                    models.TextField(max_length=200, verbose_name="Описание"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="promotions/", verbose_name="Изображение"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Статус"),
                ),
                ("created_ad", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
            },
        ),
    ]
