# Generated by Django 6.0.4 on 2026-04-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pool", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actions",
            old_name="created_ad",
            new_name="created_at",
        ),
    ]
