# Generated by Django 6.0.4 on 2026-04-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pool", "0002_rename_created_ad_actions_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Имя")),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Номер телефона"),
                ),
                (
                    "use_messenger",
                    models.BooleanField(
                        default=False, verbose_name="сСвязаться в месенджере"
                    ),
                ),
                (
                    "messenger",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "Не выбрано"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("max_m", "Max"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="Выбранный месенджер",
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Аккаунт ватсап",
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Аккаунт телеграм",
                    ),
                ),
                (
                    "max_m",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Аккаунт макс",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
    ]
