# Generated by Django 6.0.4 on 2026-04-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pool", "0003_lead"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="max_m",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="telegram",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="whatsapp",
        ),
        migrations.AlterField(
            model_name="lead",
            name="messenger",
            field=models.CharField(
                blank=True,
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("telegram", "Telegram"),
                    ("max_m", "Max"),
                ],
                default="none",
                max_length=10,
                verbose_name="Выбранный месенджер",
            ),
        ),
    ]
